import pandas as pd
from sklearn.metrics import accuracy_score, f1_score


# -------------------------------------------------
# Load Results CSV
# -------------------------------------------------
def load_results_csv(path: str = "evaluation/results.csv") -> pd.DataFrame:
    """
    Loads the evaluation results generated by the pipeline.

    Parameters
    ----------
    path : str
        Path to the results CSV.

    Returns
    -------
    pd.DataFrame
        Results DataFrame or empty DataFrame if not found.
    """
    try:
        return pd.read_csv(path)
    except FileNotFoundError:
        return pd.DataFrame()


# -------------------------------------------------
# Classification Metrics
# -------------------------------------------------
def compute_classification_metrics(y_true, y_pred) -> dict:
    """
    Computes standard classification metrics.

    Returns
    -------
    dict
        Accuracy and F1-score.
    """
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "f1_score": f1_score(y_true, y_pred, average="weighted"),
    }


# -------------------------------------------------
# Min-Max Normalization
# -------------------------------------------------
def normalize_series(series: pd.Series) -> pd.Series:
    """
    Normalizes a pandas Series to range [0, 1].

    Handles edge case where all values are equal.
    """
    if series.max() == series.min():
        return pd.Series([1.0] * len(series))
    return (series - series.min()) / (series.max() - series.min())


# -------------------------------------------------
# GreenScore Calculation
# -------------------------------------------------
def compute_greenscore(df: pd.DataFrame, weights: dict) -> pd.DataFrame:
    """
    Computes GreenScore using weighted sustainability & performance metrics.

    Metrics used:
    - Accuracy (higher is better)
    - Energy consumption (lower is better)
    - Carbon emissions in tons (lower is better)
    - Training time (lower is better)

    GreenScore Formula:
    w_acc * Acc_norm +
    w_energy * (1 - Energy_norm) +
    w_carbon * (1 - Carbon_norm) +
    w_time * (1 - Time_norm)
    """

    # Normalize metrics
    df["accuracy_norm"] = normalize_series(df["Accuracy"])
    df["energy_norm"] = normalize_series(df["Energy (kWh)"])
    df["carbon_norm"] = normalize_series(df["CO2 (tons)"])
    df["time_norm"] = normalize_series(df["Time (s)"])

    # Compute GreenScore
    df["GreenScore"] = (
        weights["accuracy"] * df["accuracy_norm"]
        + weights["energy"] * (1 - df["energy_norm"])
        + weights["carbon"] * (1 - df["carbon_norm"])
        + weights["time"] * (1 - df["time_norm"])
    )

    # Clean up intermediate columns
    df.drop(
        columns=[
            "accuracy_norm",
            "energy_norm",
            "carbon_norm",
            "time_norm",
        ],
        inplace=True,
    )

    return df
